# .github/workflows/child.yml
name: Child Workflow
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi ${{ inputs.name }}"

